version: 2.1

orbs:
  docker: circleci/docker@0.5.20

workflows:
  version: 2

  build:
    jobs:
      - docker/publish:
          cache_from: neuromation/web-shell:latest
          image: neuromation/web-shell
          tag: $(date +%Y%m%d)
          deploy: false
          context: org-dev
          filters:
            branches:
              ignore:
                - master
                - /release.*/

  master:
    jobs:
      - docker/publish:
          cache_from: neuromation/web-shell:latest
          image: neuromation/web-shell
          tag: $(date +%Y%m%d).$CIRCLE_BUILD_NUM
          context: org-dev
          filters:
            branches:
              only:
                - master

  release:
    jobs:
      - docker/publish:
          cache_from: neuromation/web-shell:latest
          image: neuromation/web-shell
          tag: $(date +%Y%m%d).$CIRCLE_BUILD_NUM,$CIRCLE_TAG,latest
          context: org-staging
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /.*/
