name: Continuous Integration

on:
  pull_request:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          make build
      
  publish:
    name: Publish auto-built image
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_SERVER: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: neuromation/web-shell
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Set up env vars 
        if: github.ref == 'refs/heads/master'
        run: |
          echo ::set-env name=TAGS::"$(date +%Y%m%d).$GITHUB_RUN_NUMBER"
     
      - name: Set up env vars for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo ::set-env name=TAGS::"latest, ${GITHUB_REF#refs/tags/}"
     
      - name: Push image
        run: |
          set -x
          docker login $DOCKER_SERVER --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          # NOTE: if branch != 'master' and no tags, then $TAGS will be empty
          for tag in $(echo $TAGS | tr "," " ")
          do
            echo docker push $IMAGE_NAME:$tag
          done
