name: Continuous Integration

on:
  pull_request:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  build_and_publish:
    name: Build image
    runs-on: ubuntu-latest
    env:
      DOCKER_SERVER: docker.io
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: neuromation/web-shell
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Docker Build
        run: |
          make build
     
      - name: Push image
        if: (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/'))
        run: |
          set -x
          docker login $DOCKER_SERVER --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

          for tag in $(echo "latest,${GITHUB_REF#refs/tags/}" | tr "," " ")
          do
            docker tag neuro-web-shell:latest $IMAGE_NAME:$tag && docker push $IMAGE_NAME:$tag
          done
