name: Continuous Integration

on:
  pull_request:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  build_and_publish:
    name: Build image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: neuromation/web-shell
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: |
          make build
      - name: Push image
        if: (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/'))
        run: |
          set -x
          for tag in $(echo "latest,${GITHUB_REF#refs/tags/}" | tr "," " ")
          do
            docker tag neuro-web-shell:latest $IMAGE_NAME:$tag && docker push $IMAGE_NAME:$tag
          done
